name: Build and publish app release

on: [ push, pull_request ]

env:
  APP_NAME: diary

jobs:
  unit_test:
    environment: development
    runs-on: ubuntu-latest
    name: "Run unit tests"
    strategy:
      matrix:
        php-versions: [ '7.4' ]
        nextcloud: [ 'stable22' ]
        database: [ 'sqlite' ]
        phpunit-version: [ '9.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite,pdo_mysql,pdo_pgsql,gd,zip
          coverage: none

      - name: Set up server with sqlite
        uses: SMillerDev/nextcloud-actions/setup-nextcloud@fae87e29aa7cdf1ea0b8033c67f60e75b10be2cd
        with:
          cron: false
          version: ${{ matrix.nextcloud }}
          database-type: ${{ matrix.database }}

      - name: Configure server with app
        uses: SMillerDev/nextcloud-actions/setup-nextcloud-app@fae87e29aa7cdf1ea0b8033c67f60e75b10be2cd
        with:
          app: ${{ env.APP_NAME }}
          check-code: false

      - name: Run composer with dev env
        run: |
          cd ../server/apps/${{ env.APP_NAME }} && composer install

      - name: Run unit tests
        run: |
          cd ../server/apps/${{ env.APP_NAME }} && vendor/bin/phpunit --testsuite unit

      - name: Run integration tests
        run: |
          cd ../server/apps/${{ env.APP_NAME }} && vendor/bin/phpunit --testsuite integration
